### ISSUE TITLE
KeyError: 'goal' when run train.py

### ISSUE THREAD

**Issue by yes5528876** [robocomp/gsoc22-socnavenv#1]
When I execute it in the terminal : $python3 train.py -e configs/empty.yaml -a dqn -c agents/DQN.py -t mlp

It shows the error:

/home/jylong/.local/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:64: UserWarning: WARN: A Box action space maximum and minimum values are equal.
  logger.warn("A Box action space maximum and minimum values are equal.")
Traceback (most recent call last):
  File "train.py", line 47, in <module>
    input_layer_size = env.observation_space["goal"].shape[0] + env.observation_space["humans"].shape[0] + env.observation_space["laptops"].shape[0] + env.observation_space["tables"].shape[0] + env.observation_space["plants"].shape[0]
  File "/home/jylong/.local/lib/python3.8/site-packages/gym/spaces/dict.py", line 194, in __getitem__
    return self.spaces[key]
KeyError: 'goal'
![Screenshot from 2023-07-08 23-49-32](https://github.com/robocomp/gsoc22-socnavenv/assets/55228217/2e090a1c-cc42-4793-a952-5a95172d5089)

Do I run the program in the wrong way?

Here's my system information:
Ubuntu 18.04
ROS melodic
python 3.8.0
gym 0.26.2
gymnasium 0.28.1
socnavgym 0.1.0

Thank you for your effort.

**Comment by sushant1212** [comment]
Hi, thanks for raising the issue. This repository is now being maintained [here](https://github.com/gnns4hri/SocNavGym/tree/main). Please raise an issue there if you still face errors.
